# Generated by Django 2.2.1 on 2020-03-24 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('cer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credential_id', models.CharField(max_length=50)),
                ('credential_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Certification',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('edu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('exp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='general',
            fields=[
                ('cv_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('certification', models.ManyToManyField(to='curvit.certification')),
                ('education', models.ManyToManyField(to='curvit.education')),
                ('experience', models.ManyToManyField(to='curvit.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='volunteering',
            fields=[
                ('vol_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('cause', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_cv', to='curvit.general')),
            ],
            options={
                'verbose_name_plural': 'Volunteering',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='general',
            name='volunteering',
            field=models.ManyToManyField(to='curvit.volunteering'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_cv', to='curvit.general'),
        ),
        migrations.AddField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_cv', to='curvit.general'),
        ),
        migrations.AddField(
            model_name='certification',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cer_cv', to='curvit.general'),
        ),
    ]
