# Generated by Django 3.0.2 on 2020-02-08 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('cer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credential_id', models.CharField(max_length=50)),
                ('credential_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Certification',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('edu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('exp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='volunteering',
            fields=[
                ('vol_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('cause', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Volunteering',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='general',
            fields=[
                ('cv_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('certification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curvit.certification')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curvit.education')),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curvit.experience')),
                ('volunteering', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curvit.volunteering')),
            ],
        ),
    ]
