# Generated by Django 2.2.1 on 2020-04-02 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('keywords', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tutorial_menu',
            fields=[
                ('menu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255, null=True)),
                ('items', models.TextField(null=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tutorial Menu',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('tutor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_lastmodified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorial.tutorial_menu')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.subject')),
            ],
            options={
                'verbose_name_plural': 'Tutorial Content',
                'ordering': ['-time_lastmodified'],
            },
        ),
    ]
