# Generated by Django 3.0.2 on 2020-02-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_lastmodified'], 'verbose_name_plural': 'Blog Content'},
        ),
    ]
